require('dotenv').config();

const {
  JWTSECRET,
  PORT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FRONTEND_REDIRCT,
  GOOGLE_BACKEND_BASEURL,
  PROJECT_ID,
  COMPUTER_REGION,
  MODEL_ID,
  SCORE_THRESHOLD,
} = process.env;

module.exports = {
  PORT,
  JWTSECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FRONTEND_REDIRCT,
  GOOGLE_BACKEND_BASEURL,
  PROJECT_ID,
  COMPUTER_REGION,
  MODEL_ID,
  SCORE_THRESHOLD,
};
