const {
  JWTSECRET,
  PORT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FRONTEND_REDIRCT,
  GOOGLE_BACKEND_BASEURL,
} = process.env;

module.exports = {
  PORT,
  JWTSECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FRONTEND_REDIRCT,
  GOOGLE_BACKEND_BASEURL,
};
